#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f f1cycle.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace f1cycle.sv --exe f1cycle_tb.cpp

# build C++ projecct via make automatically generated by Verilator
make -j -C obj_dir/ -f Vf1cycle.mk Vf1cycle

# run executable simulation file
obj_dir/Vf1cycle